### ISSUE TITLE
Enable-NagiosServiceNotification results in "The hostname could not be parsed."

### ISSUE THREAD

**Issue by PDunbarCGI** [wasserja/MrANagios#3]
Looks like $url is passed to Invoke-NagiosRequest rather than $NagiosCoreUrl

https://github.com/wasserja/MrANagios/blob/18081c9931705b898ed4b78b7d6d88e9137e8d79/Enable-NagiosServiceNotification.ps1#L52

**Comment by wasserja** [comment]
Fixed, and thank you.
